### ISSUE TITLE
Combining lpy and lispy

### ISSUE THREAD

**Issue by guibor** [abo-abo/lpy#28]
Hi abo-abo - when I activate lispy-mode and lpy together, most lpy functionality ceases to function. Is there a way you recommend to work with both modes in the same buffer?

Thanks!

**Comment by guibor** [comment]
(to be precise, the pspecial- functions no longer are called)

**Comment by abo-abo** [comment]
In which situation would you need `lispy` and `lpy` at the same time?

Because they compete for the same bindings:

- <kbd>j</kbd> calls `special-lispy-down`
- <kbd>j</kbd> calls `pspecial-lpy-down`

If you have both of them at the same time, you can maybe use `lispy-raise-minor-mode` to decide which keymap takes priority.

**Comment by guibor** [comment]
I was interested in using the paredit and more advanced transformations.

Also, in lispy they are used whenever one is in list-editing mode. So for example, lispy-different works at the beginning of any sexp, but lpy only at the beginning of a statement (correct me if I'm wrong).

Does this make sense?

**Comment by abo-abo** [comment]
> I was interested in using the paredit and more advanced transformations.

You were planning to do this in Python? I don't think many of the advanced transformations will work for Python.

Can you give an example of what you're trying to do?

**Comment by guibor** [comment]
Let's say using ">" and "<" to slurp and barf.

Probably should just use lpy-raise-minor-mode or just rebind those keys and that's it.

**Comment by abo-abo** [comment]
That's a good solution for now, I think.
